-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 21:48:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kurvan1112_qfv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kurvan1112_qfv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kurvan1112_qfv` DEFAULT CHARACTER SET utf8 ;
USE `kurvan1112_qfv` ;

-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `r` TINYINT UNSIGNED NOT NULL,
  `g` TINYINT UNSIGNED NOT NULL,
  `b` TINYINT UNSIGNED NOT NULL,
  `money` INT NULL DEFAULT 0,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`));
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_id` INT NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  `r` TINYINT UNSIGNED NULL,
  `g` TINYINT UNSIGNED NULL,
  `b` TINYINT UNSIGNED NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_province_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `kurvan1112_qfv`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `kurvan1112_qfv`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `kurvan1112_qfv`;
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (1, 'ハンガリー', 249, 126, 98, 44, NOW());
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (2, 'フランス', 20, 50, 210, 19, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (3, 'イングランド', 193, 26, 14, 47, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (4, 'リトアニア', 154, 69, 116, 41, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (5, 'カスティーリャ', 193, 171, 8, 29, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (6, 'オーストリア', 220, 220, 220, 15, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (7, 'ヴィネツィア', 54, 167, 156, 17, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (8, 'アラゴン', 166, 68, 72, 20, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (9, 'ナポリ', 100, 50, 150, 101, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (10, 'オスマン', 26, 203, 120, 52, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (11, 'ボヘミア', 161, 139, 40, 11, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (12, 'チュートン騎士団', 102, 105, 104, 10, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (13, 'ポーランド', 197, 92, 106, 23, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (14, 'デンマーク', 190, 70, 70, 10, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (15, 'ボスニア', 240, 167, 130, 8, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (16, 'セルビア', 166, 72, 57, 12, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (17, 'ワラキア', 161, 126, 128, 6, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (18, 'モルダヴィア', 136, 157, 23, 9, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (19, 'スウェーデン', 8, 82, 165, 33, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (20, 'リヴォニア騎士団', 125, 30, 100, 12, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (21, 'ポルトガル', 57, 160, 101, 12, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (22, 'ノルウェー', 117, 165, 188, 18, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (23, 'ジェノヴァ', 218, 215, 56, 6, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (24, 'ブルターニュ', 118, 99, 151, 5, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (25, 'バーデン', 117, 161, 67, 2, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (26, 'ホルシュタイン', 220, 150, 158, 3, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (27, '教皇領', 211, 220, 178, 6, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (28, 'ポメラニア', 61, 136, 66, 5, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (29, 'シレジア', 84, 166, 93, 3, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (30, 'マゾフシェ', 195, 149, 155, 5, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (31, 'フリースラント', 165, 89, 27, 3, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (32, '東フリースラント', 190, 32, 16, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (33, 'オルデンブルク', 147, 130, 118, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (34, 'ブレーメン', 33, 101, 137, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (35, 'フェルデン', 227, 211, 34, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (36, 'ハンブルク', 227, 95, 7, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (37, 'リューネブルク', 135, 109, 147, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (38, 'ザクセン＝ラウエンブルク', 79, 139, 99, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (39, 'リューベック', 156, 179, 189, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (40, 'メクレンブルク', 55, 140, 143, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (41, 'アーヘン', 157, 51, 167, 1, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (42, 'ホラント', 156, 96, 100, 3, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (43, 'ブラバント', 118, 193, 153, 4, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (44, 'ヘルレ', 139, 66, 97, 2, '');
INSERT INTO `kurvan1112_qfv`.`country` (`id`, `name`, `r`, `g`, `b`, `money`, `timestamp`) VALUES (45, '明', 179, 128, 104, 2, '');

COMMIT;

