-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 15:20:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kurvan1112_qfv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kurvan1112_qfv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kurvan1112_qfv` DEFAULT CHARACTER SET utf8 ;
USE `kurvan1112_qfv` ;

-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`country` (
  `countryId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `r` TINYINT UNSIGNED NOT NULL,
  `g` TINYINT UNSIGNED NOT NULL,
  `b` TINYINT UNSIGNED NOT NULL,
  `money` INT NULL DEFAULT 0,
  `timestamp` DATETIME NOT NULL DEFAULT 0,
  `military` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`countryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`province` (
  `provinceId` INT NOT NULL AUTO_INCREMENT,
  `x` INT NULL,
  `y` INT NULL,
  `r` TINYINT UNSIGNED NULL,
  `g` TINYINT UNSIGNED NULL,
  `b` TINYINT UNSIGNED NULL,
  `timestamp` DATETIME NOT NULL,
  `countryId` INT NOT NULL,
  PRIMARY KEY (`provinceId`),
  INDEX `fk_province_country_idx` (`countryId` ASC) VISIBLE,
  CONSTRAINT `fk_province_country`
    FOREIGN KEY (`countryId`)
    REFERENCES `kurvan1112_qfv`.`country` (`countryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`war`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`war` (
  `countryIdA` INT NOT NULL,
  `countryIdB` INT NOT NULL,
  PRIMARY KEY (`countryIdA`, `countryIdB`),
  INDEX `fk_diplomacy_country1_idx` (`countryIdA` ASC) VISIBLE,
  INDEX `fk_diplomacy_country2_idx` (`countryIdB` ASC) VISIBLE,
  CONSTRAINT `fk_diplomacy_country1`
    FOREIGN KEY (`countryIdA`)
    REFERENCES `kurvan1112_qfv`.`country` (`countryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diplomacy_country2`
    FOREIGN KEY (`countryIdB`)
    REFERENCES `kurvan1112_qfv`.`country` (`countryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`claim` (
  `countryIdA` INT NOT NULL,
  `countryIdB` INT NOT NULL,
  `claim` INT NULL,
  PRIMARY KEY (`countryIdA`, `countryIdB`),
  INDEX `fk_claim_country2_idx` (`countryIdB` ASC) VISIBLE,
  CONSTRAINT `fk_claim_country1`
    FOREIGN KEY (`countryIdA`)
    REFERENCES `kurvan1112_qfv`.`country` (`countryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claim_country2`
    FOREIGN KEY (`countryIdB`)
    REFERENCES `kurvan1112_qfv`.`country` (`countryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kurvan1112_qfv`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kurvan1112_qfv`.`log` (
  `time` DATETIME NOT NULL,
  `text` VARCHAR(200) NULL);
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `kurvan1112_qfv`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `kurvan1112_qfv`;
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (1, 'ハンガリー', 249, 126, 98, 44, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (2, 'フランス', 20, 50, 210, 19, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (3, 'イングランド', 193, 26, 14, 47, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (4, 'リトアニア', 154, 69, 116, 41, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (5, 'カスティーリャ', 193, 171, 8, 29, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (6, 'オーストリア', 220, 220, 220, 15, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (7, 'ヴィネツィア', 54, 167, 156, 17, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (8, 'アラゴン', 166, 68, 72, 20, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (9, 'ナポリ', 100, 50, 150, 101, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (10, 'オスマン', 26, 203, 120, 52, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (11, 'ボヘミア', 161, 139, 40, 11, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (12, 'チュートン騎士団', 102, 105, 104, 10, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (13, 'ポーランド', 197, 92, 106, 23, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (14, 'デンマーク', 190, 70, 70, 10, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (15, 'ボスニア', 240, 167, 130, 8, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (16, 'セルビア', 166, 72, 57, 12, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (17, 'ワラキア', 161, 126, 128, 6, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (18, 'モルダヴィア', 136, 157, 23, 9, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (19, 'スウェーデン', 8, 82, 165, 33, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (20, 'リヴォニア騎士団', 125, 30, 100, 12, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (21, 'ポルトガル', 57, 160, 101, 12, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (22, 'ノルウェー', 117, 165, 188, 18, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (23, 'ジェノヴァ', 218, 215, 56, 6, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (24, 'ブルターニュ', 118, 99, 151, 5, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (25, 'バーデン', 117, 161, 67, 2, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (26, 'ホルシュタイン', 220, 150, 158, 3, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (27, '教皇領', 211, 220, 178, 6, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (28, 'ポメラニア', 61, 136, 66, 5, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (29, 'シレジア', 84, 166, 93, 3, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (30, 'マゾフシェ', 195, 149, 155, 5, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (31, 'フリースラント', 165, 89, 27, 3, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (32, '東フリースラント', 190, 32, 16, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (33, 'オルデンブルク', 147, 130, 118, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (34, 'ブレーメン', 33, 101, 137, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (35, 'フェルデン', 227, 211, 34, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (36, 'ハンブルク', 227, 95, 7, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (37, 'リューネブルク', 135, 109, 147, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (38, 'ザクセン＝ラウエンブルク', 79, 139, 99, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (39, 'リューベック', 156, 179, 189, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (40, 'メクレンブルク', 55, 140, 143, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (41, 'アーヘン', 157, 51, 167, 1, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (42, 'ホラント', 156, 96, 100, 3, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (43, 'ブラバント', 118, 193, 153, 4, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (44, 'ヘルレ', 139, 66, 97, 2, 'NOW()', NULL);
INSERT INTO `kurvan1112_qfv`.`country` (`countryId`, `name`, `r`, `g`, `b`, `money`, `timestamp`, `military`) VALUES (45, '明', 179, 128, 104, 2, 'NOW()', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `kurvan1112_qfv`.`province`
-- -----------------------------------------------------
START TRANSACTION;
USE `kurvan1112_qfv`;
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (1, 3093, 586, 207, 223, 223, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (2, 3085, 596, 176, 33, 33, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (3, 3105, 603, 132, 97, 101, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (4, 3114, 582, 81, 224, 224, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (5, 3121, 567, 208, 97, 224, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (6, 3087, 576, 113, 95, 93, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (7, 3096, 569, 208, 97, 97, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (8, 3119, 564, 81, 224, 97, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (9, 3069, 590, 113, 97, 128, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (10, 3067, 582, 240, 224, 1, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (11, 3096, 555, 144, 224, 224, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (12, 3113, 561, 81, 48, 106, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (13, 3142, 545, 32, 192, 0, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (14, 3077, 555, 81, 97, 97, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (15, 3162, 564, 208, 224, 97, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (16, 3147, 579, 16, 159, 159, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (17, 3131, 595, 80, 96, 223, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (18, 3125, 602, 144, 160, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (19, 3065, 607, 18, 77, 115, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (20, 3055, 613, 113, 160, 65, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (21, 3044, 621, 240, 33, 192, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (22, 3053, 641, 113, 160, 192, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (23, 3153, 593, 81, 97, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (24, 3161, 583, 144, 33, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (25, 3136, 615, 144, 224, 33, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (26, 3151, 628, 17, 97, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (27, 3171, 608, 208, 97, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (28, 3166, 622, 208, 224, 33, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (29, 3178, 593, 208, 224, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (30, 3186, 585, 176, 97, 97, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (31, 3192, 595, 49, 97, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (32, 3191, 611, 81, 224, 160, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (33, 3206, 596, 175, 96, 159, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (34, 3204, 617, 48, 96, 96, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (35, 3126, 619, 98, 105, 152, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (36, 3111, 615, 17, 224, 33, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (37, 3090, 612, 207, 32, 32, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (38, 3074, 617, 81, 160, 33, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (39, 3093, 619, 144, 97, 33, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (40, 3063, 619, 112, 223, 0, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (41, 3078, 623, 16, 96, 32, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (42, 3116, 631, 144, 33, 97, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (43, 3100, 627, 128, 207, 0, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (44, 2845, 575, 16, 223, 0, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (45, 2849, 592, 144, 224, 0, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (46, 2833, 586, 136, 98, 119, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (47, 2837, 564, 144, 160, 192, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (48, 2842, 601, 80, 160, 192, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (49, 2823, 659, 48, 96, 128, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (50, 2812, 669, 16, 96, 64, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (51, 2848, 666, 207, 159, 191, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (52, 2864, 653, 144, 96, 128, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (53, 2853, 644, 16, 96, 128, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (54, 2834, 650, 176, 224, 0, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (55, 2829, 641, 48, 224, 0, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (56, 2832, 625, 176, 96, 0, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (57, 2827, 614, 48, 96, 0, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (58, 2798, 609, 208, 160, 64, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (59, 2813, 621, 80, 32, 192, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (60, 2817, 600, 208, 32, 192, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (61, 2789, 598, 63, 116, 175, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (62, 2797, 507, 128, 0, 32, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (63, 2819, 506, 98, 89, 147, 'NOW()', 2);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (64, 2790, 508, 224, 96, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (65, 2816, 504, 98, 89, 147, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (66, 2816, 506, 98, 89, 147, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (67, 2819, 506, 98, 89, 147, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (68, 2813, 493, 96, 160, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (69, 2813, 493, 96, 160, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (70, 2822, 477, 224, 32, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (71, 2799, 496, 224, 224, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (72, 2770, 513, 96, 96, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (73, 2744, 516, 96, 160, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (74, 2760, 503, 224, 224, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (75, 2796, 442, 224, 96, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (76, 2743, 485, 160, 160, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (77, 2767, 472, 160, 33, 176, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (78, 2755, 492, 32, 32, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (79, 2754, 482, 32, 160, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (80, 2772, 490, 224, 32, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (81, 2789, 490, 224, 160, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (82, 2785, 496, 96, 224, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (83, 2801, 480, 140, 102, 123, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (84, 2782, 484, 96, 32, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (85, 2705, 456, 160, 224, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (86, 2792, 477, 160, 160, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (87, 2784, 467, 224, 224, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (88, 2774, 468, 32, 160, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (89, 2802, 467, 96, 224, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (90, 2786, 454, 134, 176, 33, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (91, 2751, 464, 160, 32, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (92, 2736, 442, 19, 114, 99, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (93, 2769, 461, 101, 97, 124, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (94, 2766, 450, 224, 224, 0, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (95, 2780, 451, 96, 96, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (96, 2783, 426, 96, 96, 0, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (97, 2757, 440, 96, 224, 0, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (98, 2759, 427, 224, 96, 0, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (99, 2788, 658, 240, 32, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (100, 2793, 638, 240, 160, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (101, 2802, 644, 112, 160, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (102, 2791, 548, 144, 160, 64, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (103, 2803, 556, 16, 32, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (104, 2796, 566, 48, 224, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (105, 2814, 569, 176, 224, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (106, 2820, 539, 144, 32, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (107, 2840, 514, 224, 160, 192, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (108, 2818, 544, 176, 96, 128, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (109, 3192, 413, 168, 255, 81, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (110, 3169, 407, 192, 160, 160, 'NOW()', 3);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (111, 3171, 414, 192, 160, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (112, 3147, 405, 128, 96, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (113, 3172, 415, 192, 160, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (114, 3161, 417, 192, 160, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (115, 3186, 437, 1, 97, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (116, 3196, 441, 65, 224, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (117, 3173, 430, 0, 224, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (118, 3183, 461, 64, 96, 32, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (119, 3213, 464, 224, 97, 118, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (120, 3285, 599, 113, 97, 33, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (121, 3267, 582, 113, 224, 33, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (122, 3279, 550, 240, 97, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (123, 3246, 504, 17, 33, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (124, 3224, 478, 65, 97, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (125, 3323, 589, 176, 33, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (126, 3320, 574, 240, 224, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (127, 3306, 549, 114, 98, 145, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (128, 3339, 573, 113, 224, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (129, 3339, 533, 113, 65, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (130, 3279, 523, 1, 224, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (131, 3301, 503, 224, 128, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (132, 3268, 496, 128, 223, 223, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (133, 3259, 468, 128, 224, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (134, 3224, 441, 128, 224, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (135, 3243, 419, 128, 97, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (136, 3267, 415, 1, 97, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (137, 3249, 452, 1, 97, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (138, 3268, 465, 65, 160, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (139, 3294, 479, 128, 97, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (140, 3388, 538, 240, 97, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (141, 3380, 508, 64, 223, 223, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (142, 3367, 498, 192, 224, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (143, 3273, 421, 192, 160, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (144, 3293, 452, 1, 224, 97, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (145, 3321, 468, 188, 4, 65, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (146, 3260, 556, 240, 224, 33, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (147, 3219, 501, 224, 1, 224, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (148, 3182, 479, 191, 223, 32, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (149, 3166, 476, 192, 97, 33, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (150, 2750, 712, 48, 32, 128, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (151, 2734, 710, 112, 32, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (152, 2733, 696, 80, 224, 192, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (153, 2719, 691, 208, 96, 192, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (154, 2711, 665, 80, 96, 192, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (155, 2683, 664, 208, 224, 64, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (156, 2684, 683, 80, 224, 64, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (157, 2713, 707, 176, 32, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (158, 2708, 729, 48, 160, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (159, 2719, 790, 78, 84, 100, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (160, 2703, 774, 208, 96, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (161, 2716, 744, 80, 96, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (162, 2744, 678, 112, 160, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (163, 2740, 663, 240, 160, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (164, 2765, 667, 112, 32, 128, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (165, 2759, 684, 158, 201, 184, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (166, 2763, 697, 240, 32, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (167, 2771, 705, 176, 160, 128, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (168, 2781, 769, 113, 21, 139, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (169, 2777, 758, 98, 104, 120, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (170, 2776, 742, 160, 48, 64, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (171, 2769, 725, 176, 32, 128, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (172, 2756, 729, 176, 160, 0, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (173, 2748, 737, 128, 16, 160, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (174, 2725, 761, 128, 144, 32, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (175, 2713, 773, 128, 16, 32, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (176, 2757, 754, 0, 16, 160, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (177, 2564, 942, 32, 239, 1, 'NOW()', 5);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (178, 3053, 567, 17, 128, 160, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (179, 3037, 579, 17, 1, 160, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (180, 3019, 571, 144, 1, 160, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (181, 3048, 593, 176, 97, 65, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (182, 3069, 572, 48, 160, 32, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (183, 3059, 558, 49, 97, 65, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (184, 3046, 556, 169, 121, 59, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (185, 3030, 596, 143, 128, 32, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (186, 3021, 608, 48, 96, 191, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (187, 3037, 607, 176, 224, 64, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (188, 3045, 603, 49, 224, 65, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (189, 2990, 595, 208, 64, 224, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (190, 3002, 594, 240, 224, 192, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (191, 2978, 585, 81, 192, 224, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (192, 2982, 609, 208, 191, 96, 'NOW()', 6);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (193, 3002, 617, 176, 1, 160, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (194, 3009, 609, 85, 72, 102, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (195, 2993, 616, 81, 65, 224, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (196, 3015, 608, 16, 128, 33, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (197, 3023, 629, 176, 97, 192, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (198, 3062, 655, 208, 160, 33, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (199, 3041, 640, 239, 160, 192, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (200, 3030, 623, 240, 160, 64, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (201, 3021, 615, 144, 0, 33, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (202, 2982, 622, 48, 128, 160, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (203, 2958, 611, 134, 122, 144, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (204, 2968, 624, 80, 192, 96, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (205, 2992, 627, 176, 128, 160, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (206, 3111, 704, 199, 113, 224, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (207, 3199, 812, 96, 16, 160, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (208, 3179, 810, 223, 144, 32, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (209, 3179, 750, 160, 16, 160, 'NOW()', 7);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (210, 2825, 689, 144, 96, 64, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (211, 2849, 687, 17, 224, 65, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (212, 2849, 687, 17, 224, 65, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (213, 2836, 693, 224, 192, 32, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (214, 2845, 676, 16, 96, 192, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (215, 2803, 685, 144, 96, 192, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (216, 2791, 691, 80, 96, 64, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (217, 2794, 714, 48, 160, 128, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (218, 2799, 742, 143, 223, 128, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (219, 2851, 731, 96, 240, 128, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (220, 2797, 753, 223, 239, 128, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (221, 2806, 713, 208, 96, 64, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (222, 2816, 703, 177, 233, 121, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (223, 2947, 716, 48, 160, 64, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (224, 2947, 733, 128, 208, 32, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (225, 3031, 800, 1, 81, 33, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (226, 3017, 767, 192, 144, 160, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (227, 3029, 777, 0, 208, 32, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (228, 3029, 777, 0, 208, 32, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (229, 3033, 762, 128, 81, 32, 'NOW()', 8);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (230, 3050, 697, 112, 64, 32, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (231, 3059, 717, 120, 84, 96, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (232, 3061, 736, 192, 80, 224, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (233, 3054, 756, 192, 16, 32, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (234, 3068, 707, 48, 32, 159, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (235, 3081, 715, 64, 80, 223, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (236, 3048, 716, 64, 144, 160, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (237, 3032, 703, 176, 32, 64, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (238, 3018, 696, 14, 139, 204, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (290, 3037, 532, 113, 224, 65, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (291, 3025, 552, 240, 224, 65, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (292, 3010, 534, 240, 97, 65, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (293, 3012, 527, 113, 97, 65, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (294, 3060, 546, 239, 96, 128, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (295, 3054, 527, 144, 128, 160, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (296, 3034, 517, 29, 107, 148, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (297, 3069, 530, 113, 224, 128, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (298, 3052, 511, 192, 1, 33, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (299, 3080, 530, 240, 224, 128, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (300, 3093, 539, 16, 223, 223, 'NOW()', 11);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (301, 3130, 433, 65, 33, 160, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (302, 3132, 447, 191, 159, 32, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (303, 3132, 447, 191, 159, 32, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (304, 3098, 444, 128, 160, 160, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (305, 3094, 453, 148, 80, 0, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (306, 3109, 447, 122, 96, 97, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (307, 3100, 467, 65, 160, 33, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (308, 3156, 434, 192, 32, 160, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (309, 3143, 417, 64, 160, 160, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (310, 3162, 448, 128, 159, 96, 'NOW()', 12);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (311, 3065, 484, 33, 65, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (312, 3082, 499, 65, 224, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (313, 3082, 499, 65, 224, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (314, 3084, 464, 192, 33, 33, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (315, 3121, 533, 17, 224, 97, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (316, 3124, 541, 17, 97, 224, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (317, 3146, 536, 144, 224, 96, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (318, 3169, 540, 143, 159, 32, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (319, 3187, 553, 126, 221, 158, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (320, 3208, 568, 49, 160, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (321, 3228, 547, 113, 97, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (322, 3203, 552, 176, 33, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (323, 3184, 528, 17, 160, 33, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (324, 3158, 510, 81, 160, 224, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (325, 3132, 508, 96, 0, 223, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (326, 3091, 499, 192, 224, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (327, 3115, 502, 192, 97, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (328, 3124, 516, 208, 160, 224, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (329, 3110, 532, 144, 96, 96, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (330, 3061, 464, 1, 128, 160, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (331, 3104, 535, 144, 97, 224, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (332, 3100, 492, 87, 126, 228, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (333, 2950, 402, 0, 64, 223, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (334, 2963, 374, 0, 191, 223, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (335, 2961, 399, 128, 65, 224, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (336, 3018, 407, 192, 65, 97, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (337, 3027, 399, 192, 192, 97, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (338, 3095, 373, 33, 192, 224, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (339, 2994, 416, 128, 192, 224, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (340, 2943, 415, 148, 70, 143, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (341, 2969, 417, 116, 112, 139, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (342, 3039, 422, 144, 0, 224, 'NOW()', 14);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (343, 3072, 636, 80, 32, 159, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (344, 3077, 650, 208, 33, 160, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (345, 3064, 637, 240, 97, 1, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (346, 3086, 650, 81, 160, 160, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (347, 3088, 665, 144, 33, 224, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (348, 3095, 639, 208, 160, 160, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (349, 3096, 657, 17, 33, 224, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (350, 3099, 667, 245, 246, 194, 'NOW()', 15);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (351, 3113, 639, 16, 160, 96, 'NOW()', 1);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (352, 3149, 650, 144, 97, 160, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (353, 3130, 654, 144, 160, 97, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (354, 3119, 651, 237, 186, 32, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (355, 3145, 662, 208, 33, 224, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (356, 3151, 673, 98, 167, 48, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (357, 3134, 672, 208, 33, 97, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (358, 3124, 663, 157, 255, 175, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (359, 3119, 671, 161, 47, 130, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (360, 3129, 681, 165, 211, 169, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (361, 3104, 675, 140, 98, 146, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (362, 3100, 679, 144, 160, 224, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (363, 3111, 675, 68, 110, 132, 'NOW()', 16);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (365, 3210, 644, 176, 224, 32, 'NOW()', 17);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (366, 3195, 633, 224, 163, 33, 'NOW()', 17);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (367, 3172, 631, 224, 33, 33, 'NOW()', 17);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (368, 3178, 646, 81, 224, 33, 'NOW()', 17);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (369, 3232, 640, 33, 100, 224, 'NOW()', 17);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (370, 3229, 628, 49, 224, 33, 'NOW()', 17);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (371, 3251, 596, 113, 33, 97, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (372, 3263, 613, 176, 224, 160, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (373, 3228, 603, 176, 160, 224, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (374, 3218, 592, 48, 224, 160, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (375, 3200, 580, 0, 167, 244, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (376, 3226, 578, 239, 32, 96, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (377, 3241, 569, 138, 202, 155, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (378, 3239, 612, 244, 0, 69, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (379, 3253, 627, 217, 224, 33, 'NOW()', 18);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (380, 3032, 379, 65, 192, 97, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (381, 3061, 377, 64, 64, 223, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (382, 3053, 349, 192, 192, 224, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (383, 3019, 346, 160, 1, 32, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (384, 3018, 333, 1, 200, 200, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (385, 3015, 316, 160, 128, 33, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (386, 3041, 329, 248, 228, 0, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (387, 3058, 315, 1, 1, 160, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (388, 2986, 345, 65, 192, 224, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (389, 3087, 333, 96, 64, 96, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (390, 3084, 312, 196, 128, 165, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (391, 3070, 302, 97, 192, 97, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (392, 3050, 308, 160, 1, 160, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (393, 3171, 309, 224, 192, 224, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (394, 3162, 302, 224, 65, 224, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (395, 3207, 373, 128, 33, 160, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (396, 3159, 380, 128, 97, 33, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (397, 3144, 384, 74, 142, 93, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (398, 3161, 347, 96, 64, 224, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (399, 3191, 332, 128, 160, 33, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (400, 3200, 347, 1, 33, 160, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (401, 3221, 338, 1, 160, 33, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (402, 3223, 356, 191, 96, 96, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (403, 3224, 393, 191, 32, 96, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (404, 3203, 396, 1, 224, 33, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (405, 3272, 384, 0, 32, 224, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (406, 3297, 394, 192, 160, 96, 'NOW()', 20);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (407, 2695, 716, 48, 32, 163, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (408, 2694, 696, 208, 224, 192, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (409, 2676, 698, 208, 160, 0, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (410, 2673, 715, 80, 160, 0, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (411, 2686, 744, 235, 169, 53, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (412, 2675, 738, 208, 32, 0, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (413, 2680, 762, 160, 112, 128, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (414, 2676, 776, 32, 112, 128, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (415, 2672, 760, 84, 81, 100, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (416, 2665, 741, 208, 160, 128, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (417, 2700, 751, 0, 144, 32, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (418, 2691, 745, 235, 169, 53, 'NOW()', 21);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (419, 2921, 344, 251, 103, 124, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (420, 2946, 307, 96, 128, 32, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (421, 2939, 317, 96, 1, 32, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (422, 2911, 295, 224, 128, 32, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (423, 2926, 258, 64, 64, 192, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (424, 2943, 270, 96, 0, 160, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (425, 2985, 223, 192, 64, 192, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (426, 3023, 169, 192, 192, 192, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (427, 2976, 313, 192, 65, 224, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (428, 2986, 321, 149, 161, 84, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (429, 2984, 272, 32, 128, 160, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (430, 3007, 248, 65, 192, 192, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (431, 3109, 87, 97, 128, 128, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (432, 3189, 115, 224, 128, 128, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (433, 2559, 138, 128, 64, 64, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (434, 2700, 276, 139, 119, 144, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (435, 2786, 306, 1, 17, 224, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (436, 2989, 348, 65, 192, 224, 'NOW()', 22);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (437, 3072, 241, 224, 128, 1, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (438, 3087, 200, 97, 1, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (439, 3106, 146, 223, 0, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (440, 3211, 145, 224, 128, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (441, 3230, 201, 101, 124, 82, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (442, 3188, 245, 33, 65, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (443, 3266, 203, 160, 192, 0, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (444, 3216, 126, 224, 128, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (445, 3250, 230, 160, 65, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (446, 3221, 139, 224, 128, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (447, 3221, 139, 224, 128, 128, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (448, 3221, 196, 101, 124, 82, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (449, 3198, 284, 97, 192, 224, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (450, 3173, 276, 121, 211, 121, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (451, 3232, 291, 74, 100, 99, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (452, 3240, 266, 64, 192, 64, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (453, 3266, 286, 32, 128, 1, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (454, 3283, 316, 1, 160, 224, 'NOW()', 19);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (455, 2948, 683, 239, 64, 32, 'NOW()', 23);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (456, 2935, 643, 84, 114, 138, 'NOW()', 23);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (457, 2949, 640, 144, 64, 97, 'NOW()', 23);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (458, 3370, 624, 112, 96, 96, 'NOW()', 23);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (459, 3212, 753, 197, 100, 82, 'NOW()', 23);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (460, 3218, 740, 33, 144, 160, 'NOW()', 23);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (461, 2759, 562, 85, 96, 126, 'NOW()', 24);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (462, 2743, 564, 208, 224, 128, 'NOW()', 24);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (463, 2762, 573, 144, 32, 64, 'NOW()', 24);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (464, 2779, 568, 16, 160, 64, 'NOW()', 24);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (465, 2782, 585, 112, 96, 0, 'NOW()', 24);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (466, 2932, 569, 176, 128, 97, 'NOW()', 25);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (467, 2933, 558, 176, 1, 96, 'NOW()', 25);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (468, 2949, 423, 128, 192, 97, 'NOW()', 26);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (469, 2950, 432, 0, 192, 96, 'NOW()', 26);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (470, 2958, 441, 128, 65, 96, 'NOW()', 26);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (471, 3000, 691, 176, 192, 160, 'NOW()', 27);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (472, 3004, 671, 48, 64, 160, 'NOW()', 27);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (473, 3012, 659, 48, 192, 33, 'NOW()', 27);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (474, 2994, 679, 176, 64, 160, 'NOW()', 27);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (475, 2902, 648, 176, 64, 224, 'NOW()', 27);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (476, 2994, 633, 112, 128, 32, 'NOW()', 27);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (477, 3022, 686, 49, 192, 160, 'NOW()', 9);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (478, 3071, 442, 128, 1, 160, 'NOW()', 28);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (479, 3055, 457, 160, 192, 32, 'NOW()', 28);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (480, 3037, 463, 25, 174, 25, 'NOW()', 28);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (481, 3015, 450, 160, 65, 33, 'NOW()', 28);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (482, 3006, 441, 86, 116, 82, 'NOW()', 28);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (483, 3066, 504, 110, 97, 127, 'NOW()', 29);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (484, 3092, 521, 175, 159, 32, 'NOW()', 29);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (485, 3100, 526, 94, 144, 145, 'NOW()', 29);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (486, 3119, 471, 128, 33, 97, 'NOW()', 30);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (487, 3150, 469, 0, 159, 96, 'NOW()', 30);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (488, 3133, 486, 65, 97, 160, 'NOW()', 30);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (489, 3154, 486, 64, 223, 32, 'NOW()', 30);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (490, 3180, 526, 17, 160, 33, 'NOW()', 30);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (491, 3212, 516, 113, 224, 160, 'NOW()', 4);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (492, 3247, 554, 240, 224, 33, 'NOW()', 13);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (493, 2899, 462, 65, 192, 33, 'NOW()', 31);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (494, 2912, 463, 192, 192, 33, 'NOW()', 31);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (495, 2908, 470, 65, 65, 160, 'NOW()', 31);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (496, 2924, 460, 120, 75, 142, 'NOW()', 32);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (497, 2934, 464, 192, 1, 97, 'NOW()', 33);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (498, 2941, 463, 192, 128, 97, 'NOW()', 34);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (499, 2952, 464, 65, 128, 97, 'NOW()', 35);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (500, 2957, 454, 88, 114, 151, 'NOW()', 36);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (501, 2966, 471, 192, 128, 224, 'NOW()', 37);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (502, 2970, 456, 224, 0, 160, 'NOW()', 38);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (503, 2970, 446, 96, 128, 159, 'NOW()', 39);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (504, 2989, 454, 224, 128, 160, 'NOW()', 40);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (505, 2903, 521, 72, 111, 106, 'NOW()', 41);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (506, 2880, 478, 119, 119, 50, 'NOW()', 42);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (507, 2876, 489, 128, 192, 160, 'NOW()', 42);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (508, 2874, 496, 1, 192, 160, 'NOW()', 42);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (509, 2886, 494, 76, 72, 148, 'NOW()', 43);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (510, 2877, 506, 128, 0, 96, 'NOW()', 43);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (511, 2879, 513, 1, 128, 97, 'NOW()', 43);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (512, 2894, 496, 192, 192, 160, 'NOW()', 43);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (513, 2898, 486, 65, 192, 160, 'NOW()', 44);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (514, 2897, 506, 0, 0, 223, 'NOW()', 44);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (515, 4532, 860, 80, 144, 192, 'NOW()', 45);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (516, 4555, 845, 108, 192, 140, 'NOW()', 45);
INSERT INTO `kurvan1112_qfv`.`province` (`provinceId`, `x`, `y`, `r`, `g`, `b`, `timestamp`, `countryId`) VALUES (518, 2699, 754, 0, 144, 32, 'NOW()', 5);

COMMIT;

